databases:
  - name: prospection-db
    databaseName: prospection_db
    plan: free

services:
  # Backend API
  - type: web
    name: prospection-backend
    runtime: docker
    plan: free
    repo: https://github.com/HatimBenzahra/prospection-app-deploy
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: prospection-db
          property: connectionString

  # Serveur Python
  - type: web
    name: prospection-python-server
    runtime: docker
    plan: free
    repo: https://github.com/HatimBenzahra/prospection-app-deploy
    dockerfilePath: ./Dockerfile.python

  # Frontend
  - type: web
    name: prospection-frontend
    runtime: docker
    plan: free
    repo: https://github.com/HatimBenzahra/prospection-app-deploy
    dockerfilePath: ./Dockerfile.frontend