databases:
  - name: prospection-db
    databaseName: prospection_db
    plan: free

services:
  # Backend API
  - type: web
    name: prospection-backend
    runtime: docker
    plan: free
    repo: https://github.com/HatimBenzahra/prospection-app-deploy
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: prospection-db
          property: connectionString

  # Serveur Python
  - type: web
    name: prospection-python-server
    runtime: docker
    plan: free
    repo: https://github.com/HatimBenzahra/prospection-app-deploy
    dockerfilePath: ./backend/python-server/Dockerfile

  # Frontend
  - type: web
    name: prospection-frontend
    runtime: docker
    plan: free
    repo: https://github.com/HatimBenzahra/prospection-app-deploy
    dockerfilePath: ./moduleProspec-1dc4f634c6c14f0913f8052d2523c56f04d7738b/Dockerfile